name: Deploy to WordPress.org

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Disable xDebug - fixes PHP Fatal Error for `i18n make-pot`
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Install NPM and Composer Dependencies
        run: npm install

      - name: Run Production Task
        run: npm run production

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: dist/advanced-backgrounds/
          SLUG: advanced-backgrounds
